
<html><head>
                <meta charset="utf-8">
                <script src="../../libs/js/jquery.min.js"></script>
                <script src="../../libs/js/bootstrap.min.js"></script>
                <link rel="stylesheet" href="../../libs/mysheets/style.css">
                <link rel="stylesheet" href="../../libs/fonts/material-icon.css">
                <link rel="stylesheet" href="../../libs/stylesheets/bootstrap.min.css">
                <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
                <link rel="stylesheet" href="../custom.css">
              </head><body>
  <div class="container">
    <div class="container-form"><form method="POST" action="/rocket/<?php echo $this->view->rocket[0]->getId(); ?>/update">
  <label>Id</label>
  <input type="text" name="id" class="form-control" value="<?php echo $this->view->rocket[0]->getId(); ?>">
  <label>Codigo</label>
  <input type="text" name="codigo" class="form-control" value="<?php echo $this->view->rocket[0]->getCodigo(); ?>">
  <label>Altura</label>
  <input type="text" name="altura" class="form-control" value="<?php echo $this->view->rocket[0]->getAltura(); ?>">
  <label>Largura</label>
  <input type="text" name="largura" class="form-control" value="<?php echo $this->view->rocket[0]->getLargura(); ?>">
  <label>Peso</label>
  <input type="text" name="peso" class="form-control" value="<?php echo $this->view->rocket[0]->getPeso(); ?>"><input type="submit">
</form></div>
  </div>
  </body>
</html>