
                <html><head>
                <meta charset="utf-8">
                <script src="../../libs/js/jquery.min.js"></script>
                <script src="../../libs/js/bootstrap.min.js"></script>
                <link rel="stylesheet" href="../../libs/mysheets/style.css">
                <link rel="stylesheet" href="../../libs/fonts/material-icon.css">
                <link rel="stylesheet" href="../../libs/stylesheets/bootstrap.min.css">
                <link rel="stylesheet" href="custom.css">
              </head><body>
                  <div class="container">
                    <div class="container-form"><form method="POST" action="/fornecedor/insert"><label>id</label>
                    <input type="text" name="id" class="form-control"><label>nome</label>
                    <input type="text" name="nome" class="form-control"><label>cpf</label>
                    <input type="text" name="cpf" class="form-control"><input type="submit"></form></div>
                  </div>
                  </body>
                </html>