<header class="objects-header">
                    <div class="row">
                        <div class="col-md-2 linha-header text-center">
                            <span class="titulo-painel-adminitrativo"><a href="/">Painel Administrativo</a></span>
                        </div>
                        <div class="col-md-4">
                        <nav class="navbar"><a href="/usuario" class="btn btn-primary">usuario</a><a href="/produto" class="btn btn-primary">produto</a><a href="/fornecedor" class="btn btn-primary">fornecedor</a><a href="/rocket" class="btn btn-primary">rocket</a></nav>
              </div>
          </div>
        </header>