
                <html><head>
                <meta charset="utf-8">
                <script src="../../libs/js/jquery.min.js"></script>
                <script src="../../libs/js/bootstrap.min.js"></script>
                <link rel="stylesheet" href="../../libs/mysheets/style.css">
                <link rel="stylesheet" href="../../libs/fonts/material-icon.css">
                <link rel="stylesheet" href="../../libs/stylesheets/bootstrap.min.css">
                <link rel="stylesheet" href="custom.css">
              </head><body>
                  <?php require_once __DIR__ . "\..\header.phtml" ?>
                  <div class="container">
                    <div class="row">
                      <div class="col-md-12">
                      <a href="produto/cadastrar" class="btn btn-primary">
                      <span class="fa fa-plus" aria-hidden="true"></span>
                      Incluir
                  </a>
                      </div>
                    </div>
                    <div class="table-responsive">
                      <table class="table table-striped tabela-consulta">
                          <thead>
                              <tr>
                                  <th><?php echo "produto"; ?></th>
                              </tr>
                          </thead>
                          <tbody>
                              <tr>
                                <?php foreach ($this->view->produto as $produto): ?>
                                <td> <?php echo $produto->getId(); ?> </td>
                                <td> <?php echo $produto->getDescricao(); ?> </td>
                                <td class="acoes">
                                    <div class="dropdown">
                                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Ação
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                            <a title="Alterar" href="" class="dropdown-item">Alterar</a>
                                            <form class="form-acao-excluir" action="" method="post">
                                                <button class="dropdown-item" title="Excluir" type="submit">Excluir</button>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                                <?php endforeach; ?>
                              </tr>
                              <tr>
                                  <td colspan="3">Nenhum resultado encontrado</td>
                              </tr>
                          </tbody>
                      </table>
                  </div>
                  </div>
                </body>
              </html>