
                  <?php require_once __DIR__ . "\..\header.phtml" ?>

                    <div class="table-responsive">

                    
                    <div style="margin-top: 20px" align="right" class="container">
                    <div  class="row">
                      <div class="col-md-12">
                      <a href="produto/cadastrar" class="btn btn-success">
                      <span class="fa fa-plus" aria-hidden="true"></span>
                      Incluir
                      </a>
                      </div>
                    </div>
                      <table style="margin-top: 10px" class="table table-striped tabela-consulta">
                          <thead>
                              <tr align="center">
                                  <th>Id</th><th>Descricao</th><th>Ncm</th><th>Estoque</th><th> Ações </th>
                              </tr>
                          </thead>
                          <tbody>
                              <?php foreach ($this->view->produto as $produto): ?>
                                <tr>
                                  <td align="center" style="vertical-align: middle;"><?php echo $produto->getid(); ?> </td><td align="center" style="vertical-align: middle;"><?php echo $produto->getdescricao(); ?> </td><td align="center" style="vertical-align: middle;"><?php echo $produto->getncm(); ?> </td><td align="center" style="vertical-align: middle;"><?php echo $produto->getestoque(); ?> </td>
                                  <td align="center" class="actions">
                                      <div style="margin-bottom: 5px;">
                                        <a href="produto/<?php echo $produto->getId(); ?>/findById" id="botao-alterar" class="btn btn-primary">Alterar</a>
                                      </div>
                                      <div>
                                        <a href="produto/<?php echo $produto->getId(); ?>/delete" id="botao-excluir" class="btn btn-danger">Excluir</a>
                                      </div>
                                  </td>
                                </tr>
                              <?php endforeach; ?>
                          </tbody>
                      </table>
                  </div>
                  </div>