
                <html><head>
                <meta charset="utf-8">
                <script src="../../libs/js/jquery.min.js"></script>
                <script src="../../libs/js/bootstrap.min.js"></script>
                <link rel="stylesheet" href="../../libs/mysheets/style.css">
                <link rel="stylesheet" href="../../libs/fonts/material-icon.css">
                <link rel="stylesheet" href="../../libs/stylesheets/bootstrap.min.css">
                <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
                <link rel="stylesheet" href="../custom.css">
              </head><body>
                  <div class="container">
                    <div class="container-form"><form method="POST" action="/produto/insert">  <div class="form-group"><label>Id</label>
                    <input type="text" name="id" class="form-control"></div>  <div class="form-group"><label>Descricao</label>
                    <input type="text" name="descricao" class="form-control"></div>  <div class="form-group"><label>Ncm</label>
                    <input type="text" name="ncm" class="form-control"></div>  <div class="form-group"><label>Estoque</label>
                    <input type="text" name="estoque" class="form-control"></div><button type="submit" class="btn btn-primary">Salvar</button></form></div>
                  </div>
                  </body>
                </html>