
<html><head>
                <meta charset="utf-8">
                <script src="../../libs/js/jquery.min.js"></script>
                <script src="../../libs/js/bootstrap.min.js"></script>
                <link rel="stylesheet" href="../../libs/mysheets/style.css">
                <link rel="stylesheet" href="../../libs/fonts/material-icon.css">
                <link rel="stylesheet" href="../../libs/stylesheets/bootstrap.min.css">
                <link rel="stylesheet" href="custom.css">
              </head><body>
  <div class="container">
    <div class="container-form"><form method="POST" action="/produto/<?php echo $this->view->produto[0]->getId(); ?>/update">
  <label>Id</label>
  <input type="text" name="id" class="form-control" value="<?php echo $this->view->produto[0]->getId(); ?>">
  <label>Descricao</label>
  <input type="text" name="descricao" class="form-control" value="<?php echo $this->view->produto[0]->getDescricao(); ?>">
  <label>Ncm</label>
  <input type="text" name="ncm" class="form-control" value="<?php echo $this->view->produto[0]->getNcm(); ?>">
  <label>Estoque</label>
  <input type="text" name="estoque" class="form-control" value="<?php echo $this->view->produto[0]->getEstoque(); ?>"><input type="submit">
</form></div>
  </div>
  </body>
</html>