
                  <?php require_once __DIR__ . "\..\header.phtml" ?>
                  <div class="container">
                    <div class="row">
                      <div class="col-md-12">
                      <a href="usuario/cadastrar" class="btn btn-primary">
                      <span class="fa fa-plus" aria-hidden="true"></span>
                      Incluir
                  </a>
                      </div>
                    </div>
                    <div class="table-responsive">
                      <table class="table table-striped tabela-consulta">
                          <thead>
                              <tr>
                                  <th><?php echo "usuario"; ?></th>
                              </tr>
                          </thead>
                          <tbody>
                              <?php foreach ($this->view->usuario as $usuario): ?>
                                <tr>
                                  <th> <?php echo $usuario->getId(); ?> </th>
                                  <th> <?php echo $usuario->getNome(); ?> </th>
                                  <th class="acoes">
                                      <div>
                                        <a href="usuario/<?php echo $usuario->getId(); ?>/findById" id="botao-alterar" class="btn btn-primary">Alterar</a>
                                      </div>
                                      <div>
                                        <a href="usuario/<?php echo $usuario->getId(); ?>/delete" id="botao-excluir" class="btn btn-danger">Excluir</a>
                                      </div>
                                  </th>
                                </tr>
                              <?php endforeach; ?>
                          </tbody>
                      </table>
                  </div>
                  </div>