
                <html><head>
                <meta charset="utf-8">
                <script src="../../libs/js/jquery.min.js"></script>
                <script src="../../libs/js/bootstrap.min.js"></script>
                <link rel="stylesheet" href="../../libs/mysheets/style.css">
                <link rel="stylesheet" href="../../libs/fonts/material-icon.css">
                <link rel="stylesheet" href="../../libs/stylesheets/bootstrap.min.css">
                <link rel="stylesheet" href="custom.css">
              </head><body>
                  <?php require_once __DIR__ . "\..\header.phtml" ?>
                  <div class="container">
                    <div class="row">
                      <div class="col-md-12">
                      <a href="usuario/cadastrar" class="btn btn-primary">
                      <span class="fa fa-plus" aria-hidden="true"></span>
                      Incluir
                  </a>
                      </div>
                    </div>
                    <div class="table-responsive">
                      <table class="table table-striped tabela-consulta">
                          <thead>
                              <tr>
                                  <th><?php echo "usuario"; ?></th>
                              </tr>
                          </thead>
                          <tbody>
                              <tr>
                                <?php foreach ($this->view->usuario as $usuario): ?>
                                <td> <?php echo $usuario->getId(); ?> </td>
                                <td> <?php echo $usuario->getNome(); ?> </td>
                                <td class="acoes">
                                    <div>
                                      <a href="" id="botao-alterar" class="btn btn-primary">Alterar</a>
                                    </div>
                                    <div>
                                      <a href="usuario/<?php echo $usuario->getId(); ?>/delete" id="botao-excluir" class="btn btn-danger">Excluir</a>
                                    </div>
                                </td>
                                <?php endforeach; ?>
                              </tr>
                              <tr>
                                  <td colspan="3">Nenhum resultado encontrado</td>
                              </tr>
                          </tbody>
                      </table>
                  </div>
                  </div>
                </body>
              </html>